/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "stest.ts" instead.
 */

#include <check.h>

#line 1 "stest.ts"
#include "buf.h"

START_TEST(test_capacity_and_size_init)
{
#line 4
	float *a = 0;
	ck_assert_msg(buf_capacity(a) == 0, "test_capacity_init");
	ck_assert_msg(buf_size(a) == 0, "test_size_init");

}
END_TEST

START_TEST(test_size_1_and_value)
{
#line 9
	float *a = 0;
	buf_push(a, 1.3f);
	ck_assert_msg(buf_size(a) == 1, "test_size_1");
	ck_assert_msg(a[0] == (float)1.3f, "test_value");
	buf_free(a);

}
END_TEST

START_TEST(test_clear_and_clear_not_free)
{
#line 16
	float *a = 0;
	buf_push(a, 1.3f);
	buf_clear(a);
	ck_assert_msg(buf_size(a) == 0, "test_clear");
	ck_assert_msg(a != 0, "test_clear_not_free");
	buf_free(a);

}
END_TEST

START_TEST(test_free)
{
#line 24
	float *a = 0;
	buf_push(a, 1.3f);
	buf_free(a);
	ck_assert_msg(a == 0, test_free);

}
END_TEST

START_TEST(test_clear_empty_and_clear_no_op)
{
#line 30
	float *a = 0;
	buf_push(a, 1.3f);
	buf_free(a);
	buf_clear(a);
	ck_assert_msg(buf_size(a) == 0, "test_clear_empty");
	ck_assert_msg(a == 0, "test_clear_no_op");

}
END_TEST

START_TEST(test_size_and_match)
{
#line 38
	long *ai = 0;
	for (int i = 0; i < 10000; i++)
		buf_push(ai, i);
	ck_assert_msg(buf_size(ai) == 10000, "test_size_10000");
	int match = 0;
    for (int i = 0; i < (int)(buf_size(ai)); i++)
        match += ai[i] == i;
	ck_assert_msg(match == 10000, "test_match_10000");
	buf_free(ai);

}
END_TEST

START_TEST(test_grow_and_trunc)
{
#line 49
	long *ai = 0;
	buf_grow(ai, 1000);
	ck_assert_msg(buf_capacity(ai) == 1000, "test_row_1000");
	ck_assert_msg(buf_size(ai) == 0, "test_size_0_grow");
	buf_trunc(ai, 100);
	ck_assert_msg(buf_capacity(ai) == 100, "test_trunc_100");
	buf_free(ai);

}
END_TEST

START_TEST(test_pop_and_trunc)
{
#line 58
	float *a = 0;
	buf_push(a, 1.1);
    buf_push(a, 1.2);
    buf_push(a, 1.3);
    buf_push(a, 1.4);
	ck_assert_msg(buf_size(a) == 4, "test_size_4");
	ck_assert_msg(buf_pop(a) == (float)1.4f, "test_pop_3");
	buf_trunc(a, 3);
	ck_assert_msg(buf_size(a) == 3, "test_size_3");
	ck_assert_msg(buf_pop(a) == (float)1.3f, "test_pop_2");
	ck_assert_msg(buf_pop(a) == (float)1.2f, "test_pop_1");
	ck_assert_msg(buf_pop(a) == (float)1.1f, "test_pop_1");
	ck_assert_msg(buf_size(a) == 0, "test_size_0_pop");
	buf_free(a);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_capacity_and_size_init);
    tcase_add_test(tc1_1, test_size_1_and_value);
    tcase_add_test(tc1_1, test_clear_and_clear_not_free);
    tcase_add_test(tc1_1, test_free);
    tcase_add_test(tc1_1, test_clear_empty_and_clear_no_op);
    tcase_add_test(tc1_1, test_size_and_match);
    tcase_add_test(tc1_1, test_grow_and_trunc);
    tcase_add_test(tc1_1, test_pop_and_trunc);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
